{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-forge
  version: {{ version|replace("-", "_") }}

source:
  fn: forge_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/forge_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/forge/forge_{{ version }}.tar.gz
  sha256: 8a57396adc21970f57a13916ed2335d6eb35a5e29f09ee3e80f3a93298fe4e5e

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rlang
  run:
    - r-base
    - r-rlang

test:
  commands:
    - $R -e "library('forge')"           # [not win]
    - "\"%R%\" -e \"library('forge')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=forge
  license: Apache-2-0
  summary: Helper functions with a consistent interface to coerce and verify the types and shapes
    of values for input checking.
  license_family: APACHE

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
