# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Wm42WQ334Hr2gmHVfkEEsba4cAaz4pn+WX8lJs53+tY6CubycRLQVq/UWhZPOLOoYAT+MazmlOWMuSDL8i8kKx3+1qM2vSBXpKSTqMqyGZXY1Yc5O+Xk7E4R4+sxI8Z/3h55J2Y4SK9rJQoXaiN9baEzZzKU5+s+h5UREs3Byq4KaZ0rKsEe031F5K/Kdy/F7dNzlt8hQ79YLyMjLiSj+3jf/hUxYERYZFWaDCJWpFraX+YF4fOFZQO/l9I5UUFFXGZ0mXZGFUuxvPFj26g2zN3vlegXfW7Th2/FG0YsjQ2ZVx67WJiN1hlNTN/6IvseUI6UaNQzJhwcXf6dD4UK79J9X2udklHI1QOPOzsTrFeS8iEdFCkdcvLo9r5qO1fHoBm3dMD+k3YdxIU/Gcfq0yuDRGFkypKPf2UhayKWCYj7ix5x/dmC6VsgpSXC4Q8oT+O8o4MBInxVgLJKXNRqs3XvcxSrnpR4Ih7UQy8ecuL98PDv1bFWKpGRG52YJUYN8sjOWdD5AFL27imPJJQfJzgrfXuELJ/1SjoLiqD8SIEAJ6hf9VC2fosINvtecHx+IzNUjjub4MHvduMXnF9BBtCCHrGwbxbV+RgKYUgqiOJ4hRWGXcJlUJwL/rjsjPdp/qFKCpyP++JkS2adQJkeEZR7OKsjSJX2GtZiT22f+Yg="

matrix:
  include:
    - env: CONFIG=linux_r_base3.6target_platformlinux-64 UPLOAD_PACKAGES=True PLATFORM=linux-64 DOCKER_IMAGE=condaforge/linux-anvil-comp7
      os: linux
      arch: amd64

    - env: CONFIG=linux_r_base4.0target_platformlinux-64 UPLOAD_PACKAGES=True PLATFORM=linux-64 DOCKER_IMAGE=condaforge/linux-anvil-comp7
      os: linux
      arch: amd64

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi